# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MegaHack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MegaHack

  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'SideMenu'
	
end
